Modul 1  praktikum datamining
Manipulasi array menggunakan numpy

In [4]:
import numpy as np


#Kode 1

f. Buatlah array 2D berikut menggunakan numpy

In [14]:
aray = np.array([[4, 4, 5],[7, 6, 4],[9, 7, 4],[6, 3, 7]])
print(aray)

[[4 4 5]
 [7 6 4]
 [9 7 4]
 [6 3 7]]


g. Buatlah array 3D berikut menggunakan numpy

In [15]:
aray = np.array([
    [[7, 8, 5],[4, 7, 7],[7, 1, 9],[5, 4, 10]], 
    [[2, 1, 2],[9, 8, 5],[3, 7, 3],[4, 9, 9]],
    [[2, 9, 3],[2, 4, 8],[1, 6, 6],[8, 1, 3]]
])
print(aray)

[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]


# Kode 2

d. Tambahkan angka 1 pada setiap bilangan di baris ganjil array berikut. kemudian tambahkan angka
2 pada setiap bilangan di kolom genap array berikut.

In [10]:
aray1 = np.array([
    [1, 8, 8, 2], 
    [8, 2, 1, 2],
    [10, 1, 4, 7],
    [1, 4, 7, 8],
    [8, 2, 3, 4]
])
aray2 = np.array([
    [1, 1, 1, 1],
    [0, 0, 0, 0],
    [1, 1, 1, 1],
    [0, 0, 0, 0],
    [1, 1, 1, 1]
])
aray3 = np.array([
    [0, 2, 0, 2],
    [0, 2, 0, 2],
    [0, 2, 0, 2],
    [0, 2, 0, 2],
    [0, 2, 0, 2]
])
print(aray1+aray2+aray3)

[[ 2 11  9  5]
 [ 8  4  1  4]
 [11  4  5 10]
 [ 1  6  7 10]
 [ 9  5  4  7]]


e. Baliklah sumbu z array 3D berikut


In [11]:
aray = np.array([
    [[7, 8, 5], [4, 7, 7], [7, 1, 9], [5, 4, 10]],
    [[2, 1, 2], [9, 8, 5], [3, 7, 3], [4, 9, 9]],
    [[2, 9, 3], [2, 4, 8], [1, 6, 6], [8, 1, 3]]
])
print(aray[::-1])

[[[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]]


f. Ubahlah array pada soal e menjadi array 2D berukuran 6 x 6 (hint : gunakan perintah reshape)


In [12]:
aray = np.array([
    [[7, 8, 5], [4, 7, 7], [7, 1, 9], [5, 4, 10]],
    [[2, 1, 2], [9, 8, 5], [3, 7, 3], [4, 9, 9]],
    [[2, 9, 3], [2, 4, 8], [1, 6, 6], [8, 1, 3]]
])
print(aray.shape)
np.reshape(aray, (6,6,))

(3, 4, 3)


array([[ 7,  8,  5,  4,  7,  7],
       [ 7,  1,  9,  5,  4, 10],
       [ 2,  1,  2,  9,  8,  5],
       [ 3,  7,  3,  4,  9,  9],
       [ 2,  9,  3,  2,  4,  8],
       [ 1,  6,  6,  8,  1,  3]])

# Kode 3


e. Ubahlah matris kiri menjadi matriks sebelah kanan


In [13]:
aray = np.array([
    [5, 10, 10, 7],
    [7, 8, 4, 10],
    [9, 10, 2, 5],
    [1, 8, 9, 3],
    [6, 10, 5, 2],
    [4, 6, 9, 4]
])
arayf = np.array([
    [9, 3, 1, 8,],
    [5, 2, 6, 10],
    [9, 4, 4, 6,],
    [10, 7, 5,10],
    [4, 10, 7, 8],
    [2, 5, 9,10,]
])
aray = np.array([
    [5, 10, 10, 7],
    [7, 8, 4, 10],
    [9, 10, 2, 5],
    [1, 8, 9, 3],
    [6, 10, 5, 2],
    [4, 6, 9, 4]
])
#Array dibagi mjd 4 
araybaru1 = np.hsplit(aray, 2)
araybaru2 = np.vsplit(araybaru1[0], 2)
araybaru3 = np.vsplit(araybaru1[1], 2)
#Menggabungkan array
araybaru4 = np.hstack((araybaru3[1], araybaru2[1]))
araybaru5 = np.hstack((araybaru3[0], araybaru2[0]))
arayf = np.vstack((araybaru4, araybaru5))
print(arayf)

[[ 9  3  1  8]
 [ 5  2  6 10]
 [ 9  4  4  6]
 [10  7  5 10]
 [ 4 10  7  8]
 [ 2  5  9 10]]
